import numpy as np
from subprocess import call
import numpy as np
from astropy.io import fits
import sys
import os
os.chdir('/Volumes/Nikhil/SWIFT/New_cutout') #Path to the folder that store the Swift cutouts using the code Cutout_filter.py

"""
This code uses Source Extractor to mask all the sources in the cutout flux images so that
the remnaing image can be used to measure the background sky counts.
"""


call(['sex'])

#define paths
path_to_txt_file = '/Users/Nikhil/code/Newtext/' #Path to the text file that contains all MaNGA Ids for the specific filter
path_to_swift_cutouts = '/Volumes/Nikhil/SWIFT/New_cutout/' #Path to the folder that store the Swift cutouts using the code Cutout_filter.py
path_to_store_segmented_images = '/Volumes/Nikhil/SWIFT/New_SEG/' #Path where you wish to store the masked images generated by Source Extractor

with open(path_to_txt_file+'W1_ID.txt') as f:
   Line = [line.rstrip('\n') for line in open(path_to_txt_file+'W1_ID.txt')]


for id in range (0,np.shape(Line)[0]):
    hdu = fits.open(path_to_swift_cutouts+'UVW1_cutout_'+str(Line[id])+'.fits')
    call(['sex',path_to_swift_cutouts+'UVW1_cutout_'+str(Line[id])+'.fits'])
    call(['mv','segmentation.fits',path_to_store_segmented_images+str(Line[id])+'_UVW1_seg.fits'])
    call(['rm','segmentation.fits'])
    call(['rm','apertures.fits'])
    call(['rm','cat.fits'])
    call(['rm','objects.fits'])
